import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Le Monde",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className={poppins.className}>
      <body>{children}</body>
    </html>
  );
}
